destination: ./jekyll-aid-blog
pygments: true
markdown: rdiscount
exclude: mkdocument
lsi: true
permalink: /articles/:title.html
# leave blank for /
url_root: 
# Options used in Jekyll-base
#base_dir: /
#ga_id: UA_XXXXXXXX-1
#google_search_api_key: 1238975398735
#google_search_site_url: fastr.github.com
#title_prefix: 
